### PR TITLE
Use node-pre-gyp to distribute pre-built binaries

### PR DESCRIPTION
**Pull request by darora**
On a test machine, brings the installation time down from ~63s to ~11s

### CODE REVIEW

**Comment by maschwenk** [comment]
@darora this is awesome. @pyramation I see you've merged it, do you plan on doing a release? We'd love to test this out in our CI to reduce compilation times in our `pnpm install`

**Comment by pyramation** [comment]
please try and test it! @darora and I have released a new version 13.2.4

https://github.com/pyramation/libpg-query-node/commit/23526c7db6f20885bf8a5bfb1c306a098bc1f313

**Comment by maschwenk** [comment]
@pyramation any way I can help the release on `pgsql-parser` to use this new version? It's quite difficult for me to override at a 3 level depth.

**Comment by maschwenk** [comment]
@pyramation I was able to force it, but still got

```
.../node_modules/libpg-query install: node-pre-gyp WARN Pre-built binaries not installable for libpg-query@13.2.4 and node@14.18.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
```

**Comment by darora** [comment]
@maschwenk try now?

We'll be making a new release for pgsql-parser this week to pick this up

**Comment by pyramation** [comment]
@maschwenk @darora I just published the other module just in case

pgsql-parser@13.3.0

**Pull request merged**
